spring.application.name=Incrypt

# MySQL credentials
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/secure_notes_db}
spring.datasource.username=${DB_USER:springuser}
spring.datasource.password=${DB_PASSWORD:spring@password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpirationMs=${JWT_SECRET_MS:172800000}

frontend.url=http://localhost:3000


# Java Mail credentials
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=username@gmail.com
spring.mail.password=password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
contact.team.email=${CONTACT_TEAM_EMAIL:${spring.mail.username}}
